# Generated by Django 2.0.1 on 2018-01-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileondisk', '0004_fileinfo_fullvolpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='fullname',
        ),
    ]
