# Generated by Django 2.0.1 on 2018-01-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileondisk', '0005_remove_fileinfo_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('folder', models.TextField()),
                ('fullvolpath', models.TextField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fileondisk.Volume')),
            ],
        ),
    ]
